evaluate-commands %sh{
    plugins="$kak_config/plugins"
    mkdir -p "$plugins"
    [ ! -e "$plugins/plug.kak" ] && \
        git clone -q https://github.com/andreyorst/plug.kak.git "$plugins/plug.kak"
    printf "%s\n" "source '$plugins/plug.kak/rc/plug.kak'"
}
plug "andreyorst/plug.kak" noload
# plugins

plug "andreyorst/smarttab.kak" defer smarttab %{
	set-option global softtabstop 4 # or other preferred value
} config %{
    # these languages will use `expandtab' behavior
    hook global WinSetOption filetype=(c-sharp|rust|markdown|kak|lisp|scheme|sh|perl|julia|python) expandtab
    hook global WinSetOption filetype=yaml %{
        expandtab
        set-option buffer indentwidth 2
    }
    # these languages will use `noexpandtab' behavior
    hook global WinSetOption filetype=(makefile|gas) noexpandtab
    # these languages will use `smarttab' behavior
    hook global WinSetOption filetype=(c|cpp) smarttab
}

source "%val{config}/expand.kak"
source "%val{config}/sudo-write.kak"
source "%val{config}/vertical-selection.kak"
source "%val{config}/filetree.kak"
source "%val{config}/buffer-switcher.kak"
source "%val{config}/plugins/kak-ansi/rc/ansi.kak"
hook global BufOpenFifo \*make\* %{
    ansi-enable
}
map global normal <c-d> ': buffer-switcher<ret>'
map global normal <F1> ':filetree-switch-or-start -dirs-first -consider-gitignore<ret>'
# eval %sh{ kak-tree-sitter -dks --session $kak_session -vvvvv}
# gdb
source "%val{config}/gdb.kak"
gdb-enable-autojump
hook global GlobalSetOption gdb_session_started=true %{
    map global normal <F10>   ': gdb-next<ret>'
    map global normal <F11>   ': gdb-step<ret>'
    map global normal <s-F11> ': gdb-finish<ret>'
    map global normal <F9>    ': gdb-toggle-breakpoint<ret>'
    map global normal <F5>    ': gdb-continue<ret>'
}
hook global GlobalSetOption gdb_session_started=false %{
    unmap global normal <F10>   ': gdb-next<ret>'
    unmap global normal <F11>   ': gdb-step<ret>'
    unmap global normal <s-F11> ': gdb-finish<ret>'
    unmap global normal <F9>    ': gdb-toggle-breakpoint<ret>'
    unmap global normal <F5>    ': gdb-continue<ret>'
}
set-option global modelinefmt '%val{bufname} %val{cursor_line}:%val{cursor_char_column} {{context_info}} {{mode_info}} {red,default}%opt{gdb_indicator}{default,default}- %val{client}@[%val{session}]'

#finding
source "%val{config}/find.kak"

# General
set-option global ui_options %{ "ncurses_enable_mouse" = "true"}
hook global ModeChange .*:insert:normal %{
    set-option global idle_timeout 750
}
hook global ModeChange .*:normal:insert %{
    set-option global idle_timeout 500
}

def -hidden move-lines-down %{ exec -draft 'x<a-_><a-:>Z;ezjxdzP' }
def -hidden move-lines-up %{ exec -draft 'x<a-_><a-:><a-;>Z;bzkxdzp' }

map global normal <a-q> ': expand<ret>'
# this would be nice, but currrently doesn't work
# see https://github.com/mawww/kakoune/issues/1916
#map global insert <a-f> "<a-;>: phantom-sel-iterate-next<ret>"
#map global insert <a-F> "<a-;>: phantom-sel-iterate-prev<ret>"
# so instead, have an approximate version that uses 'i'
map global normal w     <a-i>w
map global normal <a-w> <a-i><a-w>
map global normal W     '"_s.<ret><a-i>w'
map global normal <a-W> '"_s.<ret><a-i><a-w>'
map global normal t ': move-lines-down<ret>'
map global normal T ': move-lines-up<ret>'
map global normal <c-e> f
map global normal <a-e> <a-f>
# keybindings
map global normal <backspace> <,>
# map global normal <space> <,>
map global user f ':prompt "grep in files:" %{find %val{text}}<ret>'
map global user X x
map global normal <s-tab> '<c-o>'
map global normal D ';xd'
map global normal Y ';xy'
map global normal '#' :comment-line<ret>
map global normal <c-n> '<a-i>w\"/yn'
map global normal N '<a-n>'
map global normal <a-n> '<s-n>'
map -docstring line global object l '<esc>gi<s-g>l'
map global user -docstring 'D full function' d '<a-i>w<s-m>d'
map global user -docstring 'find next match' n ':find-next-match<ret>'
map global user -docstring 'find previous match' <N> ':find-previous-match<ret>'
map global user -docstring 'focus find buffer' <F> ':try %{focus %opt{toolsclient}}<ret>'
map global normal <minus> r
map global normal <_> R
map global normal ';' ':'
map global normal ':' ';'
map global user h ': nop %sh{tmux select-pane -L}<ret>' -docstring 'tmux select left'
map global user l ': nop %sh{tmux select-pane -R}<ret>' -docstring 'tmux select right'
map global user k ': nop %sh{tmux select-pane -U}<ret>' -docstring 'tmux select up'
map global user j ': nop %sh{tmux select-pane -D}<ret>' -docstring 'tmux select down'
map global user T ': tmux-focus-tools<ret>' -docstring 'focus Tools'
map global user E ': kill' -docstring 'Exit ide'

map global normal <c-m> ': make<ret>'
# Keybindings to allow goto with shift (because i'm slow)
# map global goto -docstring 'line end' <L> l
# map global goto -docstring 'line begin' <H> h
# map global goto -docstring 'buffer top' <K> k
# map global goto -docstring 'buffer end' j e
# map global goto -docstring 'buffer end' <J> j
# map global goto -docstring 'line non blank start' <I> i

addhl global/search group
hook global RegisterModified '/' %{
    # the register may not contain a valid regex
    try %{
        addhl -override global/search regex "%reg{/}" 0:SearchRegister
    } catch %{
        addhl -override global/search group
    }
}

addhl global/curword group
# highlight current word
def -hidden update-curword %{
    eval -no-hooks -save-regs / -draft %{
        try %{
            exec -save-regs '' '<a-i>w*'
            addhl -override global/curword regex "%reg{/}" 0:CurWord
        } catch %{
            addhl -override global/curword group
        }
    }
}
hook global NormalIdle '' update-curword
hook global InsertIdle '' update-curword

def align -params 1 -docstring 'align selection' %{
	execute-keys "s%arg{1}<ret>&"
}
# alias
alias global x write-quit
# softw wrap
addhl global/ wrap
addhl global/linehighlight line '%val{cursor_line}' cursorline
# commands
# more control over new command
def vnew -params .. -command-completion -docstring '
vnew [<commands>]: create a new kakoune client
The ''terminal'' alias is being used to determine the user''s preferred terminal emulator
The optional arguments are passed as commands to the new client
The window will be split vertically'\
%{
    try %{
	    hterminal kak -c %val{session} -e "%arg{@}"
    } catch %{
        fail "The 'vterminal' alias must be defined to use this command"
    }
}
def hnew -params .. -command-completion -docstring '
vnew [<commands>]: create a new kakoune client
The ''terminal'' alias is being used to determine the user''s preferr terminal emulator
The optional arguments are passed as commands to the new client
The window will be split horizontally'\
%{
    try %{
	    vterminal kak -c %val{session} -e "%arg{@}"
    } catch %{
        fail "The 'hterminal' alias must be defined to use this command"
    }
}
def vedit -file-completion -params 1 %{
    vnew edit %arg{@}
}
def hedit -file-completion -params 1 %{
    hnew edit %arg{@}
}
def shcmd -params .. -shell-completion -docstring '%sh{params}' %{
    echo %sh{"$@"}
}
source "%val{config}/julia.kak"
def vremote-julia %{
	rvtr '-Y ponet@10.255.9.115'
	nop %sh{sleep 1}
	julia-start
 	nop %sh{tmux resize-pane -y $(expr $(tmux display -p '#{window_height}') \* 80 \/ 100)}
}
def hremote-julia %{
	rhtr '-Y ponet@10.255.9.115'
	nop %sh{sleep 1}
	julia-start
 	nop %sh{tmux resize-pane -y $(expr $(tmux display -p '#{window_height}') \* 80 \/ 100)}
}

def tmux-reset-ide-julia %{
    focus tools
    # nop %sh{tmux resize-pane -y $(expr $(tmux display -p '#{window_height}') \* 80 \/ 100)}
    nop %sh{tmux resize-pane -x $(expr $(tmux display -p '#{window_width}') \* 50 \/ 100)}

    focus jump
    nop %sh{tmux resize-pane -y $(expr $(tmux display -p '#{window_height}') \* 80 \/ 100)}
    nop %sh{tmux resize-pane -x $(expr $(tmux display -p '#{window_width}') \* 50 \/ 100)}
    focus client0
    nop %sh{tmux resize-pane -y $(expr $(tmux display -p '#{window_height}') \* 80 \/ 100)}
    nop %sh{tmux resize-pane -x $(expr $(tmux display -p '#{window_width}') \* 50 \/ 100)}
}

def tmux-reset-ide-c %{

    focus client0
    nop %sh{tmux resize-pane -x $(expr $(tmux display -p '#{window_width}') \* 33 \/ 100)}
    focus jump
    nop %sh{tmux resize-pane -x $(expr $(tmux display -p '#{window_width}') \* 33 \/ 100)}
    focus tools
    # nop %sh{tmux resize-pane -y $(expr $(tmux display -p '#{window_height}') \* 80 \/ 100)}
    nop %sh{tmux resize-pane -x $(expr $(tmux display -p '#{window_width}') \* 33 \/ 100)}
    focus client0
}
def tmux-reset-ide-cs %{

    focus jump
    nop %sh{tmux resize-pane -x $(expr $(tmux display -p '#{window_width}') \* 40 \/ 100)}
    nop %sh{tmux resize-pane -y $(expr $(tmux display -p '#{window_height}') \* 80 \/ 100)}
    focus main
    nop %sh{tmux resize-pane -x $(expr $(tmux display -p '#{window_width}') \* 60 \/ 100)}
}

def tmux-reset-ide-r %{

    focus jump
    nop %sh{tmux resize-pane -x $(expr $(tmux display -p '#{window_width}') \* 50 \/ 100)}
    nop %sh{tmux resize-pane -y $(expr $(tmux display -p '#{window_height}') \* 80 \/ 100)}
    focus main
    nop %sh{tmux resize-pane -x $(expr $(tmux display -p '#{window_width}') \* 50 \/ 100)}
}

def tmux-focus-julia %{
    focus client0
    nop %sh{tmux resize-pane -y $(expr $(tmux display -p '#{window_height}') \* 10 \/ 100)}
    nop %sh{tmux select-pane -D}
}
def tmux-focus-tools %{
    focus tools
    nop %sh{tmux resize-pane -y $(expr $(tmux display -p '#{window_height}') \* 80 \/ 100)}
    nop %sh{tmux resize-pane -x $(expr $(tmux display -p '#{window_width}') \* 80 \/ 100)}
}
def tmux-focus-hover %{
    focus lsp
    nop %sh{tmux resize-pane -y $(expr $(tmux display -p '#{window_height}') \* 80 \/ 100)}
    nop %sh{tmux resize-pane -x $(expr $(tmux display -p '#{window_width}') \* 80 \/ 100)}
}

def jide %{
	vnew %{rename-client jump
	                         set global jumpclient jump
	                         hnew %{rename-client tools
	                         set global toolsclient tools
	                         nop %sh{tmux resize-pane -y $(expr $(tmux display -p '#{window_height}') \* 20 \/ 100)}
	                         focus client0}}

	focus client0
 	nop %sh{tmux resize-pane -y $(expr $(tmux display -p '#{window_height}') \* 20 \/ 100)}
	focus client0
	julia-horizontal -O3
    map global user h ':lsp-hover<ret>'
    map global user l ': nop %sh{tmux select-pane -R}<ret>' -docstring 'tmux select right'
    map global user k ': nop %sh{tmux select-pane -U}<ret>' -docstring 'tmux select up'
    map global user j ': nop %sh{tmux select-pane -D}<ret>' -docstring 'tmux select down'
    map global user J ': tmux-focus-julia<ret>' -docstring 'focus Julia'
    map global user T ': tmux-focus-tools<ret>' -docstring 'focus Tools'
    map global user <space> ": tmux-reset-ide-julia<ret>" -docstring 'reset ide windows'
	# rename-client julia-repl
	focus client0
}

def cide %{
	vnew %{rename-client jump
	                         set global jumpclient jump
	                         vnew %{rename-client tools
	                         set global toolsclient tools
	                         nop %sh{tmux resize-pane -y $(expr $(tmux display -p '#{window_height}') \* 33 \/ 100)}
	                         focus client0}}

	focus client0
    map global user <space> ": tmux-reset-ide-c<ret>" -docstring 'reset ide windows'
    tmux-reset-ide-c
	focus client0
}

#rust
hook global WinSetOption filetype=rust %{
	set-option buffer makecmd 'cargo'
    set-option global gdb_program 'rust-gdb'
    hook global BufCreate .*bin/.*\.rs %{
        map buffer normal <C-F5> ': nop %sh{cargo build }<ret>: gdb-start'
    }
}

hook global WinSetOption filetype=c-sharp %{
	set-option buffer makecmd 'dotnet'
	set-option buffer indentwidth 4
}

def ride %{
    rename-client main
    vnew %{
        rename-client jump
        set global jumpclient jump
    	hnew %{
        	rename-client tools
            set global toolsclient tools
            focus main
            tmux-reset-ide-cs
    	}
    }
    map global user <space> ": tmux-reset-ide-cs<ret>" -docstring 'reset ide windows'
}

def cside %{
    rename-client main
    vnew %{
        rename-client jump
        set global jumpclient jump
    	hnew %{
        	rename-client tools
            set global toolsclient tools
            focus main
            tmux-reset-ide-cs
    	}
    }
    map global user <space> ": tmux-reset-ide-cs<ret>" -docstring 'reset ide windows'
}

def jenv %{
	julia-vertical -O3
	focus client0
k}
def rjide %{
	hremote-julia
	vnew edit -scratch j
 	focus client0
}
def exit-ide %{
	repl-send-text 'exit()
'
	kill
}

# source "%val{config}/python.kak"

# def pide %{
# 	vnew %{rename-client jump
# 	                         set global jumpclient jump
# 	                         hnew %{rename-client tools
# 	                         set global toolsclient tools
# 	                         nop %sh{tmux resize-pane -y $(expr $(tmux display -p '#{window_height}') \* 20 \/ 100)}}}

# 	focus client0
#  	nop %sh{tmux resize-pane -y $(expr $(tmux display -p '#{window_height}') \* 20 \/ 100)}
# 	focus client0
# 	python-horizontal -O3
# 	# rename-client julia-repl
# 	focus client0
# }

source "%val{config}/verdi.kak"
def vide %{
	vnew  %{rename-client jump
	                         set global jumpclient jump
	                         hnew  %{rename-client tools
	                         set global toolsclient tools
	                         nop %sh{tmux resize-pane -y $(expr $(tmux display -p '#{window_height}') \* 20 \/ 100)}}}
 	nop %sh{tmux resize-pane -y $(expr $(tmux display -p '#{window_height}') \* 20 \/ 100)}
	focus client0
	verdi-horizontal
	# rename-client julia-repl
	focus client0
}

# write and delete buffer
def wdb %{
    write
    delete-buffer
}
hook -group julia-ide global WinSetOption filetype=julia %{
	map global julia i ':jide<ret>' -docstring 'start julia ide'
	map global julia R ':rjide<ret>' -docstring 'start remote julia ide'
	map global julia r ':focus julia-repl' -docstring 'focus REPL'
	map global julia E ":exit-ide<ret>" -docstring 'close ide'
}
hook -group verdi-ide global WinSetOption filetype=python %{
	map global verdi E ":exit-ide<ret>" -docstring 'close ide'
}
#julia stuff
#set-face global Search white,blue
#set-face global PrimarySelectionSearch white,blue
# Hooks
# Tab stuff
hook global BufCreate .* %{
    smarttab
}
hook global InsertCompletionShow .* %{
    try %{
        # this command temporarily removes cursors preceded by whitespace;
        # if there are no cursors left, it raises an error, does not
        # continue to execute the mapping commands, and the error is eaten
        # by the `try` command so no warning appears.
        execute-keys -draft 'h<a-K>\h<ret>'
        map window insert <tab> <c-n>
        map window insert <s-tab> <c-p>
    }
}
hook global InsertCompletionHide .* %{
    unmap window insert <tab> <c-n>
    unmap window insert <s-tab> <c-p>
}
#hook global InsertChar \t %{ exec -draft -itersel h@ }
#ok
#kk
# tmux stuff
# 
hook global KakBegin .*  %sh{
    if [ -n "$TMUX" ]; then
        echo "
            alias global focus tmux-focus
            alias global terminal tmux-terminal-horizontal
            alias global hterminal tmux-terminal-horizontal	
            alias global vterminal tmux-terminal-vertical
        "
    fi
}
#copy to system clipboard
# System clipboard handling
# ─────────────────────────
evaluate-commands %sh{
    case $(uname) in
        Linux) copy="xclip -i -sel clip"; paste="xclip -o -sel clip" ;;
        Darwin)  copy="pbcopy"; paste="pbpaste" ;;
    esac
    printf "map global user -docstring 'paste (after) from clipboard' p '!%s<ret>'\n" "$paste"
    printf "map global user -docstring 'paste (before) from clipboard' P '<a-!>%s<ret>'\n" "$paste"
    printf "map global user -docstring 'yank to clipboard' y '<a-|>%s<ret>:echo -markup %%{{Information}copied selection to X11 clipboard}<ret>'\n" "$copy"
    printf "map global user -docstring 'replace from clipboard' R '|%s<ret>'\n" "$paste"
}
set global tabstop 4
set global indentwidth 4

set global BOM none
set global eolformat lf

set global autoinfo command|onkey
set -add global ui_options terminal_set_title=no

set global scrolloff 2,5

#preserve indent level
hook global InsertChar \n %{ try %{ exec -itersel -draft ';K<a-&>' } }

def -hidden backspace-with-indentwidth %{
    eval -itersel %{
        try %{
            # will only succeed at the beginning of the buffer -> nothing to do
            exec -draft ';H<a-k>\A.\z<ret>'
        } catch %{
            # if there is nothing but horizontal whitespace between character to the left and beginning of line,
            # delete in increments of indentwidth
            exec -draft "hGh<a-k>\A[ \t]+\z<ret>s(\t| {1,%opt{indentwidth}})<ret>,dl"
        } catch %{
            # regular case, delete previous character
            exec -draft 'hd'
        }
    }
}
# map global insert <backspace> '<a-;>: backspace-with-indentwidth<ret>'
# map global insert <s-backspace> '<a-;>: backspace-with-indentwidth<ret>'

map global insert <tab> '<a-;><a-gt>'
map global insert <s-tab> '<a-;><lt>'

source "%val{config}/remote-tmux.kak"
alias global rvtr remote-tmux-repl-horizontal
alias global rhtr remote-tmux-repl-vertical
#colorscheme
colorscheme qiita
declare-option -hidden regex curword
set-face global CurWord default,rgb:26343B
hook global NormalIdle .* %{
    eval -draft %{ try %{
        exec <space><a-i>w <a-k>\A\w+\z<ret>
        set-option buffer curword "\b\Q%val{selection}\E\b"
    } catch %{
        set-option buffer curword ''
    } }
}
add-highlighter global/ dynregex '%opt{curword}' 0:CurWord
#taken from occivink kakrc
# stop c and d from yanking
# move line up down


def scratch -docstring "Open a scratch buffer" -params ..1 %{
    try %{
        eval %sh{ [ -z "$1" ] && printf fail }
        edit -scratch %arg{1}
    } catch %{
        edit -scratch *scratch*
    }
}
def kakrc -docstring "Open kakrc" %{
    edit ~/.config/kak/kakrc
}
addhl global/ number-lines -hlcursor

addhl global/ show-matching

def -hidden smart-star -params 1 %{
    try %{
        exec -draft <a-space>
        eval -no-hooks -draft -save-regs '"' %{
            exec -save-regs '' "%arg{1}""""*"
            edit -scratch *smart-star-temp*
            exec '<a-P>)<a-space>i|<esc>'
        }
        try %{ exec -buffer *smart-star-temp* -save-regs '' "%%H""%val{register}/<c-r>.<ret>" }
        db *smart-star-temp*
    } catch %{
        exec -save-regs '' """%val{register}%arg{1}"
    }
}
map global normal * ': smart-star *<ret>'
map global normal <a-*> ': smart-star <lt>a-*><ret>'
map -docstring "select 🡓"           global user v     ': select-down<ret>'
map -docstring "select 🡑"           global user <a-v> ': select-up<ret>'
map -docstring "select 🡓🡑"          global user V     ': select-vertically<ret>'
# WAKAtime
# source "%val{config}/wakatime.kak"
#powerline
plug "andreyorst/powerline.kak" defer powerline %{
    hook -once global WinCreate .* %{
        powerline-theme solarized-dark
        powerline-separator arrow
        powerline-format line_column position mode_info bufname filetype
        # powerline-toggle line_column off
    } config %{
        powerline-start
    }
}
plug 'delapouite/kakoune-cd' %{
  # Suggested mapping
  map global user c ': enter-user-mode cd<ret>' -docstring 'cd'
  # Suggested aliases
  alias global cdb change-directory-current-buffer
  alias global cdr change-directory-project-root
  alias global ecd edit-current-buffer-directory
  alias global pwd print-working-directory
}
# Suggested hook
source "%val{config}/bufferinfo.kak"
# hook global WinDisplay .* info-buffers
# Suggested mappings
#map global user b ':enter-buffers-mode<ret>'              -docstring 'buffers…'
#map global user B ':enter-user-mode -lock buffers<ret>'   -docstring 'buffers (lock)…'
# Suggested aliases
alias global bd delete-buffer
alias global bf buffer-first
alias global bl buffer-last
alias global bo buffer-only
alias global bo! buffer-only-force
map global normal q ':enter-buffers-mode<ret>'
map global buffers q ga -docstring 'alternate'
map global normal F ': eval -client main %{buffer %opt{current_bufname}}<ret>qq: focus main<ret>'
map global normal f ': eval -client jump %{buffer %opt{current_bufname}}<ret>qq'

#autosave
def autosave-start %{
	hook global -group autosave ModeChange .*:insert:.* %{
    	try %{
        	write
    	}
	}
	hook global -group autosave NormalIdle .* %{
    	try %{
        	write
    	}
    }
    hook global FocusOut .* %{ try %{
        write
} }
}
def autosave-stop %{
	remove-hooks global autosave
}
autosave-start
# Documentation Julia
def makedoc %{
	# echo '%val{buffile}\/'
    # echo %sh{julia --color=yes $kak_buffile/../make.jl}
    evaluate-commands %sh{
	    output=$(mktemp -d -t kak-temp-XXXXXXX)/fifo
	    mkfifo ${output}
	    {
	    	dir="$(dirname $kak_buffile)"
	    	julia --color=yes $dir/../make.jl &> ${output}
	    } > /dev/null 2>&1 < /dev/null &
	    echo "edit! -fifo ${output} *makedoc-output*
	    	  hook buffer BufClose .* %{nop %sh{rm -r $(dirname ${output})}}"
    }
}
#latex
hook global WinSetOption filetype=latex %{
    set-option buffer makecmd "pdflatex -output-directory %sh{echo $(dirname ${kak_buffile})} %val{buffile}"
}

#faces
#
#
hook global ModeChange .*:insert %{
	face global PrimaryCursor rgb:1B2529,rgb:E3E3E3+fg
	face global PrimaryCursorEol rgb:1B2529,rgb:E3E3E3+fg
    face global SecondaryCursor    rgb:1B2529,rgb:586e75+fg
    face global SecondaryCursorEol    rgb:1B2529,rgb:586e75+fg
    face global MatchingChar       rgb:45D4e8,rgb:586e75+b
}
hook global ModeChange .*:insert:.* %{
    face global PrimaryCursor rgb:1B2529,rgb:00f76b+fg
    face global PrimaryCursorEol rgb:1B2529,rgb:00f76b+fg
    face global SecondaryCursor    rgb:1B2529,rgb:009640+fg
    face global SecondaryCursorEol    rgb:1B2529,rgb:009640+fg
    face global MatchingChar       rgb:45D4e8,rgb:009640+b
}
#autopairs
source "%val{config}/auto-pairs.kak"
#snippets
# source "%val{config}/snippets.kak"
# source "%val{config}/snippets-directory.kak"
plug "occivink/kakoune-snippets" config %{
    set-option -add global snippets_directories "%opt{plug_install_dir}/kakoune-snippet-collection/snippets"
    hook global WinSetOption filetype=python %{
        set-option global snippets_auto_expand false
    }
    map global insert <a-tab> ":snippets-select-next-placeholders<ret>"
    # some other kakoune-snippets related configurations
}
# plug "andreyorst/kakoune-snippet-collection"
# map global user <tab> ':snippets-expand-trigger<ret>' -docstring 'snippets expand'

source "%val{config}/lsp.kak"
source "%val{config}/fortran.kak"

hook global BufCreate .*\.(f90|f95|f03|f08|F90) %{
    set-option buffer filetype fortran
}

hook global BufCreate .*\.cs %{
    set-option buffer filetype c-sharp
    set-option buffer comment_line //
    set-option buffer comment_block_begin /*
    set-option buffer comment_block_end */
    set-option buffer indentwidth 4
}

hook global WinSetOption filetype=rust %{
    snippets-directory-disable
}

def fide %{
	rename-client main
	vnew %{rename-client jump
	                         set global jumpclient jump
	                         hnew %{rename-client tools
	                         set global toolsclient tools
	                         nop %sh{tmux resize-pane -y $(expr $(tmux display -p '#{window_height}') \* 20 \/ 100)}}}

	focus main
 	nop %sh{tmux resize-pane -y $(expr $(tmux display -p '#{window_height}') \* 20 \/ 100)}
 	set-option global makecmd "echo 'source /opt/intel/bin/compilervars.sh intel64 && make pw -j 28' | bash"
	focus main
	# hnew 
	focus main
	# rename-client julia-repl
}

set-option global autoreload yes

plug "andreyorst/fzf.kak" config %{
    map global normal <c-F> ': fzf-mode<ret>'
    map global normal <c-p> ': fzf-mode<ret>b'
    map global normal <c-u> ': fzf-mode<ret>p'
    map global normal <c-f> ': fzf-mode<ret>g'
    map global normal <c-o> ': fzf-mode<ret>f'
} defer fzf-file %{
    set-option global fzf_file_command "fd" #ind . \( -path '*/.svn*' -o -path '*/.git*' -o -path '*/deps*' -o -path '*/assets/*' \) -prune -o -type f -print"
    set-option global fzf_highlight_command 'bat'
} defer fzf-grep %{
    set-option global fzf_grep_command 'rg'
} defer fzf-project %{
}

